In [0]:
#dot()函数是矩阵乘，而*则表示逐个元素相乘
import numpy as np
a = np.array([2,2,2,2,2,2,2,2,2,2])
b = np.array([[1,0,0,0],
              [1,1,1,1],
              [1,2,2,2],
              [1,2,2,2],
              [1,3,3,3],
              [1,4,4,4],
              [1,2,2,2],
              [1,3,3,3],
              [1,2,2,2],
              [1,3,3,3]])
c = np.array([0.25,0.25,0.25,0.25])

ans1 = np.dot(a,b)
print(ans1)
ans2 = a.dot(c)
print(ans2)

ans3 = a * b.T
print(ans3)
ans4 = a * c.T
print(ans4)


[20 44 44 44]


ValueError: ignored

In [0]:
#內積
c = np.array([[1,1,3,1],[6,6,6,6]])
d = np.array([[1,0,0,0],[2,3,4,5]])
print(c.shape)
print(d.shape)

e = c[0].dot(d)

(2, 4)
(2, 4)


ValueError: ignored

In [0]:
# Dropout 用法

In [0]:
import numpy as np
a = np.array([2,2,2,2,2,2,2,2,2,2])
b = np.array([[1,0,0,0],
              [1,1,1,1],
              [1,2,2,2],
              [1,2,2,2],
              [1,3,3,3],
              [1,4,4,4],
              [1,2,2,2],
              [1,3,3,3],
              [1,2,2,2],
              [1,3,3,3]])

In [3]:
b.shape

(10, 4)

In [7]:
b

array([[1, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 2, 2, 2],
       [1, 2, 2, 2],
       [1, 3, 3, 3],
       [1, 4, 4, 4],
       [1, 2, 2, 2],
       [1, 3, 3, 3],
       [1, 2, 2, 2],
       [1, 3, 3, 3]])

In [13]:
result= np.random.rand(*b.shape) < 0.1
result

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [0]:
import numpy as np
# x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)

In [4]:
import numpy as np
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3
weight_size = output_dim * np.prod(input_shape)
input_size = num_inputs * np.prod(input_shape)
test = np.linspace(-0.1, 0.5, num=input_size)


b = np.linspace(-0.3, 0.1, num=output_dim)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)

print(test.shape)
x = np.linspace(-0.1, 0.5, num=input_size).reshape(2, *(4, 5, 6))
print(x.shape)
print("w",w.shape)
y =x.reshape(x.shape[0], -1).dot(w)+b
print (y.shape)
print ("w.shape.T ",w.T.shape)
print(w)
print(w.T)




(240,)
(2, 4, 5, 6)
('w', (120, 3))
(2, 3)
('w.shape.T ', (3, 120))
[[-0.2        -0.19860724 -0.19721448]
 [-0.19582173 -0.19442897 -0.19303621]
 [-0.19164345 -0.1902507  -0.18885794]
 [-0.18746518 -0.18607242 -0.18467967]
 [-0.18328691 -0.18189415 -0.18050139]
 [-0.17910864 -0.17771588 -0.17632312]
 [-0.17493036 -0.1735376  -0.17214485]
 [-0.17075209 -0.16935933 -0.16796657]
 [-0.16657382 -0.16518106 -0.1637883 ]
 [-0.16239554 -0.16100279 -0.15961003]
 [-0.15821727 -0.15682451 -0.15543175]
 [-0.154039   -0.15264624 -0.15125348]
 [-0.14986072 -0.14846797 -0.14707521]
 [-0.14568245 -0.14428969 -0.14289694]
 [-0.14150418 -0.14011142 -0.13871866]
 [-0.13732591 -0.13593315 -0.13454039]
 [-0.13314763 -0.13175487 -0.13036212]
 [-0.12896936 -0.1275766  -0.12618384]
 [-0.12479109 -0.12339833 -0.12200557]
 [-0.12061281 -0.11922006 -0.1178273 ]
 [-0.11643454 -0.11504178 -0.11364903]
 [-0.11225627 -0.11086351 -0.10947075]
 [-0.10807799 -0.10668524 -0.10529248]
 [-0.10389972 -0.10250696 -0.101114

In [1]:
#兩個矩陣相同大小的 行跟列 互相乘積做相加 化成 2,3
import numpy as np
q = np.array([[2,2,2,0],
             [3,3,3,3]])
k = np.array([[1,1,1],
              [2,2,2],
              [3,3,3],
              [4,4,4]]
              )
print("q.shape",q.shape)
print("k.shape",k.shape)
a = q.dot(k)
print(a)
print(a.shape)

('q.shape', (2, 4))
('k.shape', (4, 3))
[[12 12 12]
 [30 30 30]]
(2, 3)


In [5]:
import tensorflow as tf
tf.reshape(k,[-1,6])

<tf.Tensor 'Reshape_2:0' shape=(2, 6) dtype=int64>

In [2]:
#兩個矩陣需要相同大小 並且對應位置做乘積 
import numpy as np
r = np.array([[2,2,2,0],
             [3,3,3,3]])
t = np.array([[1,1,1,1],
              [2,2,2,2],
              
              ]
              )
print("r.shape",r.shape)
print("t.shape",t.shape)
#b = r*t
b= np.multiply(r,t) 
print(b)
print(b.shape)
out1 = np.maximum(0, r)
print(out1)

('r.shape', (2, 4))
('t.shape', (2, 4))
[[2 2 2 0]
 [6 6 6 6]]
(2, 4)
[[2 2 2 0]
 [3 3 3 3]]


In [0]:
# dx = (x > 0) * dout   將X大於0的數值 取出來 跟dout 矩陣相乘

In [3]:
x = np.random.randn(2, 4)
#dout = np.random.randn(*t)
print("out1",out1)
print("t",t)
i = (out1 >0) * t
print(i)

('out1', array([[2, 2, 2, 0],
       [3, 3, 3, 3]]))
('t', array([[1, 1, 1, 1],
       [2, 2, 2, 2]]))
[[1 1 1 0]
 [2 2 2 2]]


In [0]:
# np.maximum(0, x - correct_class_scores[:, np.newaxis] + 1.0)

In [12]:
t = np.maximum(0, x - out1[:, np.newaxis] + 1.0)
#print(x)
print(out1)
print("out1[:, np.newaxis]",out1[:, np.newaxis] + 1.0)
#print(t)

[[2 2 2 0]
 [3 3 3 3]]
('out1[:, np.newaxis]', array([[[3., 3., 3., 1.]],

       [[4., 4., 4., 4.]]]))


In [0]:
# X = np.linspace(-5.5, 4.5, num=N*D).reshape(D, N).T

In [6]:
import numpy as np
X = np.linspace(-5.5, 4.5, num=12).reshape(4, 3).T
print(X)

[[-5.5        -2.77272727 -0.04545455  2.68181818]
 [-4.59090909 -1.86363636  0.86363636  3.59090909]
 [-3.68181818 -0.95454545  1.77272727  4.5       ]]


In [0]:
#x_pad = np.pad(x, ((0,), (0,), (pad,), (pad,)), mode='constant', constant_values=0)

In [2]:
import numpy as np
x_shape = (2, 3, 4, 4)

x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
print("x : ", x)
x_pad = np.pad(x, ((0,), (0,), (1,), (1,)), mode='constant', constant_values=0)
print(x_pad)


('x : ', array([[[[-0.1       , -0.09368421, -0.08736842, -0.08105263],
         [-0.07473684, -0.06842105, -0.06210526, -0.05578947],
         [-0.04947368, -0.04315789, -0.03684211, -0.03052632],
         [-0.02421053, -0.01789474, -0.01157895, -0.00526316]],

        [[ 0.00105263,  0.00736842,  0.01368421,  0.02      ],
         [ 0.02631579,  0.03263158,  0.03894737,  0.04526316],
         [ 0.05157895,  0.05789474,  0.06421053,  0.07052632],
         [ 0.07684211,  0.08315789,  0.08947368,  0.09578947]],

        [[ 0.10210526,  0.10842105,  0.11473684,  0.12105263],
         [ 0.12736842,  0.13368421,  0.14      ,  0.14631579],
         [ 0.15263158,  0.15894737,  0.16526316,  0.17157895],
         [ 0.17789474,  0.18421053,  0.19052632,  0.19684211]]],


       [[[ 0.20315789,  0.20947368,  0.21578947,  0.22210526],
         [ 0.22842105,  0.23473684,  0.24105263,  0.24736842],
         [ 0.25368421,  0.26      ,  0.26631579,  0.27263158],
         [ 0.27894737,  0.28526316,  0

In [12]:

stride = 2
HH =4
H=4
W=4
WW =4
pad =1
N=2
F=3

import numpy as np  
w_shape = (3, 3, 4, 4)
np.set_printoptions(threshold=np.inf) 
w = np.linspace(-0.2, 0.3, num=np.prod(w_shape)).reshape(w_shape)
b = np.linspace(-0.1, 0.2, num=3)


H_out = int(1 + (H + 2 * pad - HH) / stride)
print("H_out :",H_out)
W_out = int(1 + (W + 2 * pad - WW) / stride)
print("W_out :",W_out)
out = np.zeros((N, F, H_out, W_out))
print("x : ",x)
#zero padding      前面的數字 代表在該維度 要不要加0
#                               row      col
x_pad = np.pad(x,((0,), (0,), (pad,), (pad,)) ,mode='constant', constant_values=0)
#                                       前面1代表col 的前面   後面1 代表col 後面
print("x_pad:",x_pad)
for i in range(H_out):
       for j in range(W_out):
          #跳stride
          # 取出filter的大小 
          #                                    : 假如是4 則只會從0~3 
          x_padded_mask = x_pad[:, :, i*stride:i*stride+HH, j*stride:j*stride+WW] #(:, :, HH, WW)
          print(x_padded_mask)
          for k in range(F): # F =3   k 只會做到2
          #卷积
            print("k :",k)
            print("out.shape :",out.shape)  # (2, 3, 2, 2))
            print("x_padded_mask.shape :",x_padded_mask.shape) # (2, 3, 4, 4)
            #                         每個filter 對 每一張照片 RGB 取出同樣大小的矩陣  把三個filter 取出來的值 全部sum起來  成一個數值 接者依序放入 out矩陣內 
            out[:, k , i, j] = np.sum(x_padded_mask * w[k, :, :, :], axis=(1,2,3))   #    如果第一個維度有兩張照片  假設我沒寫0  代表第一個row 我不做相加 
print("out ",out)         
out += b[None, :, None, None]# None 相当于 numpy.newaxis  這樣才能確實與out 各個相加
print("b[None, :, None, None] :",b[None, :, None, None])



('H_out :', 2)
('W_out :', 2)
('x : ', array([[[[-0.1       , -0.09368421, -0.08736842, -0.08105263],
         [-0.07473684, -0.06842105, -0.06210526, -0.05578947],
         [-0.04947368, -0.04315789, -0.03684211, -0.03052632],
         [-0.02421053, -0.01789474, -0.01157895, -0.00526316]],

        [[ 0.00105263,  0.00736842,  0.01368421,  0.02      ],
         [ 0.02631579,  0.03263158,  0.03894737,  0.04526316],
         [ 0.05157895,  0.05789474,  0.06421053,  0.07052632],
         [ 0.07684211,  0.08315789,  0.08947368,  0.09578947]],

        [[ 0.10210526,  0.10842105,  0.11473684,  0.12105263],
         [ 0.12736842,  0.13368421,  0.14      ,  0.14631579],
         [ 0.15263158,  0.15894737,  0.16526316,  0.17157895],
         [ 0.17789474,  0.18421053,  0.19052632,  0.19684211]]],


       [[[ 0.20315789,  0.20947368,  0.21578947,  0.22210526],
         [ 0.22842105,  0.23473684,  0.24105263,  0.24736842],
         [ 0.25368421,  0.26      ,  0.26631579,  0.27263158],
        

In [74]:
""a = np.array([[[[3,1,2],[3,1,2],[3,1,2],[3,1,2]]]])
w = np.array([[[[2,2,2],[2,2,2],[2,2,2],[2,2,2]]]])
c = np.sum(a * w, axis=(0,1,2))
print("a:",a)
print("a.shape :",a.shape)
print("w:",w.shape)
print("w :",w)
print("c:",c)


('a:', array([[[[3, 1, 2],
         [3, 1, 2],
         [3, 1, 2],
         [3, 1, 2]]]]))
('a.shape :', (1, 1, 4, 3))
('w:', (1, 1, 4, 3))
('w :', array([[[[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]]]))
('c:', array([24,  8, 16]))


In [0]:
# db = np.sum(dout, axis=(0,2,3))

In [18]:
dout = np.random.randn(2, 3, 4, 5)
print("dout",dout)
print("dout.shape",dout.shape)
db = np.sum(dout, axis=(0,2,3))
print("db",db)
print("db.shape",db.shape)

('dout', array([[[[ 0.12354319,  0.31233763,  0.18529076, -0.89330127,
           0.57812458],
         [ 0.78266926, -0.848506  ,  0.31615311, -1.16778503,
          -0.83073547],
         [-1.34659746, -0.18888002, -0.73374613, -0.1937781 ,
           0.84934542],
         [-0.08191519, -0.96082971, -0.71308813, -1.32208103,
          -0.02263854]],

        [[ 1.66956017, -2.77140035,  0.40828826, -0.61917219,
          -0.40427229],
         [ 0.21756197,  0.09000249,  0.71630259, -1.52828399,
          -0.69136003],
         [-0.54885878,  1.03099736,  1.66413363, -0.16345917,
           1.14454256],
         [-0.27098953, -1.46708074, -1.3438297 ,  0.25585633,
           0.02871653]],

        [[-0.16321417, -0.29742651, -0.19802629,  1.65547656,
           1.80258945],
         [-0.76786559,  1.64139115, -1.6717671 ,  0.28470596,
           0.83620282],
         [ 0.06643961, -1.87087413,  0.78233866, -0.24199662,
           1.47094486],
         [ 0.28081987,  0.27494859,  1.08

In [0]:
# windows

In [25]:
  x_shape = (2, 3, 4, 4)
  x = np.linspace(-0.3, 0.4, num=np.prod(x_shape)).reshape(x_shape)
 
  
  dx = None
  #x, pool_param = cache
  pool_height = 2
  pool_width = 2
  stride = 2
  N, C, H, W = x.shape
  N, C, H1, W1 = dout.shape
  dx = np.zeros_like(x)
  
  for n in xrange(N):
      for c in xrange(C):
          for i in xrange(H1):
              ii = i * stride
              for j in xrange(W1):
                  jj = j * stride  
                  window = x[n,c,ii:ii+pool_height,jj:jj+pool_width]
                  dx[n,c,ii:ii+pool_height,jj:jj+pool_width] = (window==np.max(window)) * dout[n,c,i,j]
 

ValueError: ignored

In [0]:


J = set(J)
return len([s for s in S if s in J])

In [0]:
class Solution(object):
    def uniqueMorseRepresentations(self, words):
        MORSE = [".-","-...","-.-.","-..",".","..-.","--.",
                 "....","..",".---","-.-",".-..","--","-.",
                 "---",".--.","--.-",".-.","...","-","..-",
                 "...-",".--","-..-","-.--","--.."]

        seen = {"".join(MORSE[ord(c) - ord('a')] for c in word)
                for word in words}

        return len(seen)
Solution.uniqueMorseRepresentations()

In [0]:
# tensorflow

In [3]:
import tensorflow as tf
def some_method(data): 
  a = data[:,0:2] 
  print a.get_shape() 
  c = data[:,1:3]
  print c.get_shape()
  s = (a + c)
  return tf.sqrt(tf.matmul(s, tf.transpose(s)))





with tf.Session() as sess:
  fake_data = tf.constant([
      [5.0, 3.0, 7.1],
      [2.3, 4.1, 4.8],
      [2.8, 4.2, 5.6],
      [2.9, 8.3, 7.3]
  ])
  print sess.run(some_method(fake_data))


(4, 2)
(4, 2)
[[12.884487 11.878131 12.449096 15.721323]
 [11.878131 10.962208 11.489995 14.509306]
 [12.449096 11.489995 12.043255 15.207894]
 [15.721323 14.509306 15.207894 19.204166]]


In [11]:
import numpy as np
a = np.array([[[2,2,2],[2,2,2]],
              [[2,2,2],[2,2,2]],
              [[3,3,3],[4,4,4]]])
print(a.shape)

(3, 2, 3)


In [20]:
x = tf.constant([[3, 2,3],
                 [4, 5,5],
                 [6, 7,6]])
print "x.shape", x.shape
sliced = tf.slice(x, [0, 0], [3, 2])
print "sliced.shape", sliced.shape

with tf.Session() as sess:
  print "sliced:\n", sliced.eval()

x.shape (3, 3)
sliced.shape (3, 2)
sliced:
[[3 2]
 [4 5]
 [6 7]]


In [28]:
t = tf.constant([[[1],[2],[3],[4]], [[5],[6],[7],[8]]])

with tf.Session() as sess:
  print t
  print sess.run(t)
  print ("t.squeeze")
  print sess.run(tf.squeeze(t))
  print sess.run(tf.squeeze(t)).shape
  

Tensor("Const_25:0", shape=(2, 4, 1), dtype=int32)
[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]
t.squeeze
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [2]:
global h
h = 0.00001
eps = 0.0001

# f(x) to solve
def f(x):
    a_0 = 1.00000
    a_1 = 2.00000
    a_2 = 3.00000
    a_3 = 4.00000
    a_4 = 5.00000
    return a_0 + a_1 * x + a_2 * x*x + a_3 * x*x*x + a_4 * x*x*x*x

def fp(x):
    global h
    return (f(x + h) - f(x)) / h

def fpp(x):
    global h
    return (fp(x + h) - fp(x)) / h

# main
x = 2 # initial value

while True:
    fx = f(x)
    fpx = fp(x)
    xnew = x - (2.0 * fx * fpx) / (2.0 * fpx * fpx - fx * fpp(x))
    #print(xnew)
    if abs(xnew - x) <= eps: 
        print(xnew,"\n\ndone!")
        break
    x = xnew


(-0.4369861422228913, '\n\ndone!')


In [7]:
import tensorflow as tf

global h
global a
a = [1.,2.,3.,4.,5.]
h = tf.constant(0.001)
eps = tf.constant(0.001)

# f(x) to solve
def f(x):
    global a
    a_0 = tf.constant(a[0])
    a_1 = tf.constant(a[1])
    a_2 = tf.constant(a[2])
    a_3 = tf.constant(a[3]) 
    a_4 = tf.constant(a[4])
    return a_0 + a_1 * x + a_2 * x*x + a_3 * x*x*x + a_4 * x*x*x*x

def fp(x):
    global h
    return (f(x + h) - f(x)) / h

def fpp(x):
    global h
    return (fp(x + h) - fp(x)) / h

with tf.variable_scope("model",reuse = tf.AUTO_REUSE):
  x = tf.get_variable(name="x_v",initializer=2.)#,trainable = )
with tf.Session() as sess:
    while True:
        tf.global_variables_initializer().run()
        fx = f(x)
        fpx = fp(x)
        fppx = fpp(x)
        xnew = x - (2.0 * fx * fpx) / (2.0 * fpx * fpx - fx * fppx)
        print(xnew.eval())
        if abs(xnew - x).eval() <= eps.eval(): 
            print(xnew.eval(),"\n\ndone!")
            break
        x = xnew

1.0337441
0.37902188
-0.5177596
-0.6779737
4.976612
3.1529918
1.7064087
0.8844668
0.25024366
-0.9081106
-0.43760636
-0.4376736
(-0.4376736, '\n\ndone!')
