###  np.random.choice( range , 要選的數量 , p = [range 的數量] (合起來為1) , replace=boolin(說明選過的位置能不能再重複選取) ) 

In [3]:
# 0~9 中 依照後面給的機率值選取五個數
import numpy as np
np.random.choice(10, 5, p=[0, 0, 0.3, 0, 0.1,0,0,0,0,0.6])

array([9, 2, 9, 9, 4])

In [0]:
d = np.array([2,3,1,6,4,5,9])
np.random.choice(d, 3,replace=False)

array([9, 1, 6])

### Ture 可以視為是1 False 可以視為是0

In [0]:
a = 8 == 8
a == 1

True

In [0]:
True == 1

True

In [0]:
False == 0

True

###  np.flatnonzero() 找出不為 0 的 indices 

In [0]:
a = np.array([1,4,5,5,3,2,2,3])
b = 1
c = [0,0,0,0,0,0]

In [0]:
np.flatnonzero(a)

array([0, 1, 2, 3, 4, 5, 6, 7])

### np.shape (3,1) 與 (3, )的區別

In [0]:
np.zeros([3,1]),np.zeros([3,1]).shape

(array([[0.],
        [0.],
        [0.]]), (3, 1))

In [0]:
np.zeros([3,]),np.zeros([3,]).shape

(array([0., 0., 0.]), (3,))

### 矩陣相乘

In [0]:
a = np.zeros([8,1,6,1],dtype = int)
a,a.shape

(array([[[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]],
 
 
        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]],
 
 
        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]],
 
 
        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]],
 
 
        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]],
 
 
        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]],
 
 
        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]],
 
 
        [[[0],
          [0],
          [0],
          [0],
          [0],
          [0]]]]), (8, 1, 6, 1))

In [0]:
b = np.zeros([7,1,5],dtype = int)
b,b.shape

(array([[[0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0]]]), (7, 1, 5))

###### shape (8, 1, 6, 1)    x   shape  (7, 1, 5)     ====>  (8, 7, 5, 6)
###### 矩陣如果1維可以與多維做相乘

In [0]:
c = a * b
c[0],c.shape

(array([[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0

In [0]:
c1 = np.multiply(a , b)
c1[0],c1.shape

(array([[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0

In [4]:
## * 和 multuply 運算方式ㄧ樣
aaa = np.array([2,2,2])
bbb = np.array([3,3,3])
ccc = aaa * bbb
ddd = np.multiply(aaa,bbb)
print(" aaa * bbb", ccc , "\n np.multiply(aaa,bbb)" ,ddd)

 aaa * bbb [6 6 6] 
 np.multiply(aaa,bbb) [6 6 6]


### Broadcasting 矩陣運算時，會自動將矩陣extend成相依配的shape做運算
##### https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#broadcasting ( 參考網站)

In [0]:
#生成5個element為1的array
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [0]:
z = np.ones((3, 4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
# 運算過程中 a -> [[1,1,1,1],
#                [1,1,1,1],
#                [1,1,1,1],
#                [1,1,1,1]] 再做相加
a + z

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

### Reshape

In [0]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [0]:
xx = x.reshape(4, 1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [0]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9]])
print(a.shape)
a= np.reshape(a, (3,-1))
print(a)
#print(a.shape)

(4, 3)
[[1 2 3 4]
 [5 6 7 8]
 [9 7 8 9]]


### 做矩陣轉至後做矩陣相乘

In [6]:
x1 = np.arange(9.0).reshape((3, 3)).T
x2 = np.arange(3.0)
# np.multiply() 為矩陣直接indices相乘
print("x1 :\n",x1)
print("x2 :\n",x2)
np.multiply(x1, x2)


x1 :
 [[0. 3. 6.]
 [1. 4. 7.]
 [2. 5. 8.]]
x2 :
 [0. 1. 2.]


array([[ 0.,  3., 12.],
       [ 0.,  4., 14.],
       [ 0.,  5., 16.]])

In [0]:
x2

array([0., 1., 2.])

In [0]:
x1

array([[0., 3., 6.],
       [1., 4., 7.],
       [2., 5., 8.]])

In [0]:
# np.dot() 為矩陣內積
np.dot(x1,x2)

array([15., 18., 21.])

### 放在for loop 中的 [ ] 會在loop結束時清掉 

In [0]:
for i in range(10):
    cls = []
    cls.append(i)
    print(cls)
    print("===========")

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]


In [0]:
cls = []
for i in range(10):
    cls.append(i)
    print(cls)
print("===========")

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### 做歐式距離的運算(a-b)^2=a^2+b^2-2ab
##### dicts =>  -2*(X1Y1+X2Y2+....+XnYn)
##### sq1   => X_test的每個element平方 
##### sq2   => X_train的每個element平方
##### 重點！！！在做矩陣運算時需注意運算時broadcasting的矩陣大小
##### keepdims = True 為做矩陣運算時只考慮設定維度的範圍做運算 (參考網站) http://www.shuang0420.com/2016/06/26/numpy－理解keepdims=True/

In [0]:
dicts = np.zeros((3, 9))
test = np.array([[2,3,4],[1,2,3],[3,3,3]])
train = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]])



In [49]:
print("test[1] :\n",test[1])
print("test[1].shape :\n",test[1].shape)
print("train :\n",train)
print("train.shape :\n",train.shape)
print("\n")

#dicts[1,:] = np.sum((test[1] - train),axis=0,keepdims = True)    
for i in range(3):
    dicts[i,:] = np.sum((test[i] - train),axis=1)#axis=1   # 每一行test[i] - train 會得到一個數值 ,依序放入到dicts[i,:] dicts i 行的 第一個j到最後一個
    print("=======")
print(dicts)


test[1] :
 [1 2 3]
test[1].shape :
 (3,)
train :
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
train.shape :
 (9, 3)


[[6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6.]]


In [11]:
print("train.T :\n",train.T)
print("test :\n",test)
po = np.dot(test,train.T)
print("np.dot(test,train.T) :\n",po)

train.T :
 [[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
test :
 [[2 3 4]
 [1 2 3]
 [3 3 3]]
np.dot(test,train.T) :
 [[9 9 9 9 9 9 9 9 9]
 [6 6 6 6 6 6 6 6 6]
 [9 9 9 9 9 9 9 9 9]]


In [0]:
dists = np.multiply(np.dot(test,train.T),-2)
dists.shape,dists

((3, 9), array([[-18, -18, -18, -18, -18, -18, -18, -18, -18],
        [-12, -12, -12, -12, -12, -12, -12, -12, -12],
        [-18, -18, -18, -18, -18, -18, -18, -18, -18]]))

In [0]:
sq1 = np.sum(np.square(test),axis=1,keepdims = True)  #keepdims = True 不會把運算結果裝成一個維度內,保持為(3,1) 需與最後的維度做考慮

In [0]:
sq1

array([[29],
       [14],
       [27]])

In [0]:
sq2 = np.sum(np.square(train),axis=1)  #與最後的維度的column數相同,不需要keepdims = True 

In [0]:
sq2

array([3, 3, 3, 3, 3, 3, 3, 3, 3])

In [0]:
dicts = np.add(dists,sq2)

In [0]:
dicts

array([[-15, -15, -15, -15, -15, -15, -15, -15, -15],
       [ -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9],
       [-15, -15, -15, -15, -15, -15, -15, -15, -15]])

In [0]:
dicts = np.add(dists,sq1)

In [0]:
dicts

array([[11, 11, 11, 11, 11, 11, 11, 11, 11],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9]])

### 轉至 np.T

In [0]:
a = np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [0]:
a.T

array([[1, 2],
       [2, 3],
       [3, 4]])

### ＣＶ 邏輯

In [0]:
a = [1,2,3,4,5]
b = [2,4,3,2,4]
a+b

[1, 2, 3, 4, 5, 2, 4, 3, 2, 4]

In [0]:
a = list([1,2,3])
i = 1
train = a[:i]+a[i+1:]# 除了[i]以外的所有train 資料
test = a[i]
print("train" ,train)
print("test" ,test)


train [1, 3]
test 2


### Numpy-argsort (參考網站) https://www.jianshu.com/p/64c607d49528

In [0]:
# np.argsort 為印出sort完後的indices
# axis=x 為要sort的維度為哪一維 shape(n1,n2,n3,n4,n4)  
a = np.array([9, 8, 7, 6, 5, 4, 3, 1, 2])

print(a.argsort())

[7 8 6 5 4 3 2 1 0]


### Numpy array 合併

In [0]:
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B)))    # vertical stack
                           # 為垂直相加 相等於axis=0 byrow

[[1 1 1]
 [2 2 2]]


In [0]:
D = np.hstack((A,B))       # horizontal stack
                           # 為水平相加 相等於axis=1 bycolumn
print(D)

[1 1 1 2 2 2]


In [0]:
AT = np.array([1,1,1])[:,np.newaxis]
BT = np.array([2,2,2])[:,np.newaxis]
CC = np.concatenate((AT,BT,BT,AT),axis=0)
print("CC:" ,CC)
DD = np.concatenate((AT,BT,BT,AT),axis=1)
print("DD:" ,DD)

CC: [[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
DD: [[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


### np.newaxis

In [0]:
print("維度增加在前面:" ,A[np.newaxis,:],"shape: ",A[np.newaxis,:].shape)
print("維度增加在後面:\n", A[:,np.newaxis],"shape: ",A[:,np.newaxis].shape)

維度增加在前面: [[1 1 1]] shape:  (1, 3)
維度增加在後面:
 [[1]
 [1]
 [1]] shape:  (3, 1)


In [0]:
print("A:" ,A)
print("A.T:",A.T)#(n,)無法.T做轉至
print("A[:,np.newaxis]: ",A[:,np.newaxis].T) #可以做轉至(已經多了一個維度)

A: [1 1 1]
A.T: [1 1 1]
A[:,np.newaxis]:  [[1]
 [1]
 [1]]


### numpy.linalg.norm(x, ord=None(L2), axis=None, keepdims=False)

In [0]:
c = np.array([[ 1, 2, 3],
              [-1, 1, 4]])
np.linalg.norm(c, axis=0)

array([1.41421356, 2.23606798, 5.        ])

In [0]:
np.linalg.norm(c, axis=1)

array([3.74165739, 4.24264069])

In [0]:
np.linalg.norm(c, ord=1, axis=1)

array([6., 6.])

### enumerate()

In [0]:
#給一個indies
a = list(["a","s","d","f","g"])
for y, cls in enumerate(a):
    print(y, cls)

0 a
1 s
2 d
3 f
4 g


### numpy.bincount 


In [0]:
np.bincount(np.arange(5))

array([1, 1, 1, 1, 1])

In [0]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))
# 分别统计0-7分别出现的次数
# index 0 出現了1次
# index 1 出現了3次
# index 2 出現了1次......

array([1, 3, 1, 1, 0, 0, 0, 1])

In [0]:
w = np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6]) # weights
x = np.array([0, 1, 1, 3, 2, 2])
np.bincount(x, w)# 出現0的機率為0.3
                 # 出現1的機率為0.5+0.2
                 # 出現2的機率為1+(-0.6)
                 # 出現3的機率為0.7

array([0.3, 0.7, 0.4, 0.7])

### numpy.argmax()

In [0]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
np.argmax(a) #找出矩陣中最大的index

5

In [0]:
np.argmax(a, axis=0)#找出在第0軸的最大的index

array([1, 1, 1])

In [0]:
np.argmax(a, axis=1)#找出在第1軸的最大的index

array([2, 2])

### numpy.array_split

In [0]:
#將x分成3組
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]